### ISSUE TITLE
Help me....

### ISSUE THREAD

**Issue by TienIC** [cfarl/projetofullstackangularspringboot#1]
Hello. I saw you on the Brazilian game translation website. That game is called The Last Remnant. I see you have a tool to unpack and repack that game's subtitle language file. Can you share it for me? I really need it to translate the game The Last Remnant. I'm sorry for texting here, I'm afraid you won't read my message on your project web. Not to mention I have edited all the Fonts, Images and more for this game. It's just the subtitle language I don't know how to edit it.

**Comment by cfarl** [comment]
Hi, Bean!
Write a message to me, at lutitus@gmail.com
Hope you see my reply, I will erase this issue tomorrow, ok?

**Comment by TienIC** [comment]
yes ! yes!!! i will!! You are my savior. I will close it.
